spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=virginia_dev_saayam_rdbms
spring.datasource.username=postgres
spring.datasource.password=Saayam#123

cloud.aws.credentials.access-key=<your-access-key>
cloud.aws.credentials.secret-key=<your-secret-key>
cloud.aws.region.static=<your-region>
cloud.aws.stack.auto=false

sqs.url=https://sqs.<your-region>.amazonaws.com/<your-account-id>/<your-queue-name>

sns.topic.arn=arn:aws:sns:<your-region>:<your-account-id>:<your-topic-name>:<your-unique-id>

#spring.datasource.url=${DB_DEV_HOST_URL}
#spring.datasource.username=${DB_DEV_USERNAME}
#spring.datasource.password=${DB_DEV_PASSWORD}

spring.main.lazy-initialization=true
spring.datasource.hikari.initializationFailTimeout=-1
spring.datasource.hikari.minimum-idle=0

spring.jpa.hibernate.ddl-auto=none

spring.sql.init.mode=never

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param

spring.main.banner-mode=off

spring.messages.basename=lang/saayam_messages
spring.messages.encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

volunteer.service.url=http://localhost:8081