spring.datasource.url=jdbc:postgresql://<your-database-url>:5432/<your-database-name>
spring.datasource.username=<your-username>
spring.datasource.password=<your-password>

cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID:}
cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY:}
cloud.aws.region.static=${AWS_REGION:us-east-1}
cloud.aws.stack.auto=false

sqs.url=${AWS_SQS_NOTIFICATION_QUEUE_URL:}

sns.topic.arn=${AWS_SNS_TOPIC_ARN:}
ses.sender.email=${AWS_SES_SENDER_EMAIL:}

spring.datasource.url=${DB_DEV_HOST_URL}
spring.datasource.username=${DB_DEV_USERNAME}
spring.datasource.password=${DB_DEV_PASSWORD}

spring.main.lazy-initialization=true
spring.datasource.hikari.initializationFailTimeout=-1
spring.datasource.hikari.minimum-idle=0

spring.jpa.hibernate.ddl-auto=none

spring.sql.init.mode=never

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param

spring.main.banner-mode=off

spring.messages.basename=lang/saayam_messages
spring.messages.encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
